name = "agents-api"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "c8dd4182b1cf4eeebaf5202cc6c20c02"

[vars]
ALCHEMY_URL = "https://base-mainnet.g.alchemy.com/v2/2rxzAb3pSRGOv26opqwLo"
REALM_TOKEN = "0xBA2cA14375b2cECA4f04350Bd014B375Bc014ad2"
